version: "3.8"

services:

  passwork:
    image: ghcr.io/lucrasoft/passwork-docker:7.0.1
    restart: always
    depends_on:
      - mongo
    ports:
      - 7443:7443
    volumes:
      # the init folder will contain (after initial setup) the generated keys and the config.env file
      - ./init:/server/init
    networks:
      - pw

  mongo:
    image: percona/percona-server-mongodb:6.0.20
    environment:
    - PERCONA_TELEMETRY_DISABLE=1
    ports:
    - 27017:27017
    volumes:
    - ./database:/data/db
    networks:
    - pw

networks:
  pw:


