name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v3
      
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Passwork package 
      env:
        API_KEY: ${{ secrets.PASSWORK_API_KEY }}
      run: |
        mkdir passwork
        curl -o passwork.zip "https://portal.passwork.pro/api/download?rc=yes&apikey=$API_KEY"
        unzip passwork.zip -d passwork
        chmod -R 777 passwork

    - name: Read and parse version
      run: |
        raw_version=$(cat passwork/version)
        major=$((10#${raw_version:0:2}))
        minor=$((10#${raw_version:2:2}))
        patch=$((10#${raw_version:4:4}))
        version="${major}.${minor}.${patch}"
        echo "Parsed version: $version"
        echo "VERSION=$version" >> $GITHUB_ENV
        build_tag="${version}-${GITHUB_RUN_NUMBER}"
        echo "TAG_WITH_BUILD=$build_tag" >> $GITHUB_ENV

    # - name: List passwork folder
    #   run: ls -la passwork

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ghcr.io/lucrasoft/passwork-docker:${{ env.TAG_WITH_BUILD }}
          ghcr.io/lucrasoft/passwork-docker:${{ env.VERSION }}
          ghcr.io/lucrasoft/passwork-docker:latest