name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v3 

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: lucrasoft/passwork-docker:0.1
        secrets: |
            "mysecret=https://${{ secrets.PASSWORK_GIT_USERNAME }}:${{ secrets.PASSWORK_GIT_PASSWORD }}@passwork.download"
